# Generated by Django 6.1 on 2026-08-30 12:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(help_text='Reserva asociada a la opinión.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.booking')),
                ('property', models.ForeignKey(blank=True, help_text='Propiedad sobre la que se opina (si aplica).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property')),
                ('room', models.ForeignKey(blank=True, help_text='Habitación sobre la que se opina (si aplica).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.room')),
            ],
            options={
                'verbose_name': 'opinión',
                'verbose_name_plural': 'opiniones',
                'ordering': ['-created_at'],
                'unique_together': {('booking', 'property', 'room')},
            },
        ),
    ]
